// Generated by CoffeeScript 1.3.3
(function() {

  YUI({
    base: './scripts/',
    modules: {
      booking: {
        path: 'booking.js'
      },
      bookingView: {
        path: 'booking_view.js'
      },
      appView: {
        path: 'app_view.js'
      }
    }
  }).use('event-base', 'appView', function(Y) {
    return Y.on('domready', function() {
      return new Y.AppView();
    });
  });

}).call(this);
