// Generated by CoffeeScript 1.3.3
(function() {

  YUI().add('appView', function(Y) {
    return Y.AppView = Y.Base.create('appView', Y.View, [], {
      initializer: function() {
        var p, p_view;
        p = new Y.Booking({
          price: 100,
          cost: 50
        });
        p_view = new Y.BookingView({
          container: Y.Node.create('<div class="booking" />'),
          model: p
        });
        return p_view.render();
      }
    });
  }, '0.1', {
    requires: ['view', 'booking', 'bookingView']
  });

}).call(this);
