// Generated by CoffeeScript 1.3.3
(function() {

  YUI().add('bookingView', function(Y) {
    return Y.BookingView = Y.Base.create('bookingView', Y.View, [], {
      events: {
        'input': {
          change: 'update'
        }
      },
      template: 'Kosten: <input type="number" name="cost" value="{cost}" /><br />\
      Preis: <input type="number" name="price" value="{price}" /><br />\
      Gewinn: <span id="netGain">{netGain}</span>',
      initializer: function() {
        return this.get('model').after('change', this.render, this);
      },
      render: function() {
        var container, html, model;
        container = this.get('container');
        model = this.get('model');
        if (!container.inDoc()) {
          html = Y.Lang.sub(this.template, {
            cost: model.get('cost'),
            price: model.get('price'),
            netGain: model.netGain()
          });
          Y.one('#content').append(container.setHTML(html));
        } else {
          container.one("#netGain").setHTML(model.netGain());
        }
        return this;
      },
      update: function() {
        var container, cost, price;
        container = this.get('container');
        cost = container.one('input[name=\'cost\']').get('value');
        price = container.one('input[name=\'price\']').get('value');
        return this.get('model').setAttrs({
          cost: cost,
          price: price
        });
      }
    });
  }, '0.1', {
    requires: ['view', 'node']
  });

}).call(this);
